-- SQL Script to Create Token Blacklist Table
-- Run this in Supabase SQL Editor

-- Step 1: Create the table
CREATE TABLE IF NOT EXISTS public.token_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Step 2: Create an index on the token column for fast lookups
CREATE INDEX IF NOT EXISTS idx_token_blacklist_token ON public.token_blacklist(token);

-- Step 3: (Optional but recommended) Enable Row Level Security
-- We generally want the backend to access this, but good practice to enable
ALTER TABLE public.token_blacklist ENABLE ROW LEVEL SECURITY;

-- Allow all access for now (since we use service role or authenticated client in backend)
-- You might want to restrict this further in production
CREATE POLICY "Allow all access to token_blacklist" ON public.token_blacklist
    FOR ALL USING (true) WITH CHECK (true);
