import supabase from "../config/supabaseClient.js";
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";

// Test endpoint
export const me = async (req, res) => {
  res.status(200).json({
    message: "User endpoint is working!",
  });
};

// Get current logged-in user's profile
export const getCurrentUser = async (req, res) => {
  try {
    // req.user is populated by authenticateUser middleware
    const { id, reg_no, name } = req.user;
    
    // Fetch full user details from database
    const { data: user, error } = await supabase
      .from("users")
      .select("id, reg_no, name, contact, department, created_at")
      .eq("reg_no", reg_no)
      .single();

    if (error || !user) {
      return res.status(404).json({ 
        error: "User not found" 
      });
    }

    res.status(200).json({
      message: "Current user retrieved successfully",
      user: user,
    });
  } catch (error) {
    console.error("Get current user error:", error);
    res.status(500).json({ error: error.message });
  }
};

// Sign Up User (using reg_no instead of email)
export const signUp = async (req, res) => {
  const { reg_no, password, name, contact, department } = req.body;

  try {
    // 1. Validate required fields
    if (!reg_no || !password || !name) {
      return res.status(400).json({
        error: "reg_no, password, and name are required fields",
      });
    }

    // 2. Check if user already exists
    const { data: existingUser } = await supabase
      .from("users")
      .select("reg_no")
      .eq("reg_no", reg_no)
      .single();

    if (existingUser) {
      return res.status(409).json({
        error: "User with this registration number already exists",
      });
    }

    // 3. Hash the password
    const saltRounds = 10;
    const password_hash = await bcrypt.hash(password, saltRounds);

    // 4. Insert user into database (id will be auto-generated by Supabase)
    const { data: newUser, error: dbError } = await supabase
      .from("users")
      .insert([
        {
          reg_no: reg_no,
          password_hash: password_hash,
          name: name,
          contact: contact || null,
          department: department || null,
        },
      ])
      .select()
      .single();

    if (dbError) throw dbError;

    // 5. Return success (don't send password_hash back)
    const { password_hash: _, ...userWithoutPassword } = newUser;

    res.status(201).json({
      message: "User registered successfully",
      user: userWithoutPassword,
    });
  } catch (error) {
    console.error("Signup error:", error);
    res.status(500).json({ error: error.message });
  }
};

// Login User (using reg_no and password)
export const login = async (req, res) => {
  const { reg_no, password } = req.body;

  try {
    // 1. Validate required fields
    if (!reg_no || !password) {
      return res.status(400).json({
        error: "reg_no and password are required",
      });
    }

    // 2. Find user by reg_no
    const { data: user, error: fetchError } = await supabase
      .from("users")
      .select("*")
      .eq("reg_no", reg_no)
      .single();

    if (fetchError || !user) {
      return res.status(401).json({
        error: "Invalid registration number or password",
      });
    }

    // 3. Verify password
    const isPasswordValid = await bcrypt.compare(password, user.password_hash);

    if (!isPasswordValid) {
      return res.status(401).json({
        error: "Invalid registration number or password",
      });
    }

    // 4. Create JWT token with user data
    const JWT_SECRET = process.env.JWT_SECRET || "your-secret-key-change-this";
    const token = jwt.sign(
      {
        id: user.id,
        reg_no: user.reg_no,
        name: user.name,
      },
      JWT_SECRET,
      { expiresIn: "7d" } // Token expires in 7 days
    );

    // 5. Return success (don't send password_hash back)
    const { password_hash: _, ...userWithoutPassword } = user;

    res.status(200).json({
      message: "Login successful",
      token: token,
      user: userWithoutPassword,
    });
  } catch (error) {
    console.error("Login error:", error);
    res.status(500).json({ error: error.message });
  }
};

// Logout User
export const logout = async (req, res) => {
  try {
    const userName = req.user?.name || "User";
    
    // Get token from header
    const authHeader = req.headers.authorization;
    if (authHeader) {
      const token = authHeader.split(" ")[1];
      console.log("Attempting to blacklist token:", token.substring(0, 20) + "...");
      
      // Blacklist the token
      const { error } = await supabase
        .from("token_blacklist")
        .insert([{ token }]);
        
      if (error) {
        console.error("Error blacklisting token:", error);
      } else {
        console.log("Token blacklisted successfully");
      }
    } else {
      console.log("No auth header found in logout request");
    }

    res.status(200).json({
      message: `${userName} is logout successful`,
    });
  } catch (error) {
    console.error("Logout error:", error);
    res.status(500).json({ error: error.message });
  }
};
